### ISSUE TITLE
Compiled files ext.so or bundle.ext

### ISSUE THREAD

**Issue by mikevoets** [ankane/faiss-ruby#5]
We are using this gem in production and are experiencing that our deployment times have decreased because of the gem compilation on every install. We do cache `vendor/bundle` and restore it, but when this gem gets fetched and installed, it seems to have to run the compilation regardless - and this takes a long time.

We tried to do some investigation to see what's going on here, and whether the compiled file (ext.so or bundle.ext?) isn't cached properly, but after some investigation we didn't really get to a good understanding on what was going on here.

Could you give us some advice on if it is possible to cache the compiled files (like how we cache `vendor/bundle`), and what the right approach of that would be, so that we can avoid the compilation to take such a long time during deployment?

**Comment by ankane** [comment]
Hi @mikevoets, I'm not really sure how to reproduce this. Once a gem is installed, Bundler shouldn't try to reinstall it (whether it has native extensions or not), so it sounds like something is off with saving or restoring the cache.
